--INSERT INTO role
insert into role(id, name) values(2, 'ADMIN');
insert into role(id, name) values(3, 'MANAGER');
insert into role(id, name) values(4, 'SUPERADMIN');
insert into role(id, name) values(55, 'SUPERMANAGER');
--

--INSERT INFO users
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (11, 'sgilgryst0', 'anYrIx7y', 'Joni', 'Gilgryst', 'Sallyann', 'sgilgryst0@nifty.com', false, 2);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (2, 'dscapens1', 'ojG6xsu', 'Goober', 'Scapens', 'Daryl', 'dscapens1@pcworld.com', false, 3);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (3, 'dlegrice2', '50o1smq', 'Janey', 'Le Grice', 'Dru', 'dlegrice2@youtu.be', false, 4);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (4, 'jleveret3', 'yX57RquaX9', 'Emmett', 'Leveret', 'Joanie', 'jleveret3@weebly.com', false, 4);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (5, 'lcruwys4', 'caaIWo45', 'Trenna', 'Cruwys', 'Lanita', 'lcruwys4@chronoengine.com', true, 4);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (6, 'cmagrane5', 'qNqXe5Vwv4Q', 'Daloris', 'Magrane', 'Cindie', 'cmagrane5@unesco.org', false, 3);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (7, 'bvolant6', '8GdEDab0oAe', 'Lonnard', 'Volant', 'Batsheva', 'bvolant6@sitemeter.com', true, 3);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (8, 'jmeekins7', 'LRwrfvcknp', 'Oralia', 'Meekins', 'Julina', 'jmeekins7@trellian.com', false, 2);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (9, 'nkilgallon8', 'glr39gXqw1g', 'Elmo', 'Kilgallon', 'Nerissa', 'nkilgallon8@squidoo.com', false, 4);
insert into users (id, username, password, first_name, last_name, patronymic, email, status, role_id) values (10, 'awittey9', 'Cd39XW3NQ', 'Findley', 'Wittey', 'Ardra', 'awittey9@tmall.com', false, 2);
--Generated by https://www.mockaroo.com/