insert into users (id, first_name, last_name, patronymic, email, status) values (11, 'Abigail', 'Hyde-Chambers', 'ahydechambers0', 'ahydechambers0@tiny.cc', true);
insert into users (id, first_name, last_name, patronymic, email, status) values (2, 'Clemmie', 'Lomax', 'clomax1', 'clomax1@nasa.gov', false);
insert into users (id, first_name, last_name, patronymic, email, status) values (3, 'Harland', 'Cutill', 'hcutill2', 'hcutill2@ed.gov', true);
insert into users (id, first_name, last_name, patronymic, email, status) values (4, 'Timmie', 'Margery', 'tmargery3', 'tmargery3@ucoz.ru', false);
insert into users (id, first_name, last_name, patronymic, email, status) values (5, 'Ruthy', 'Kissock', 'rkissock4', 'rkissock4@nationalgeographic.com', false);
insert into users (id, first_name, last_name, patronymic, email, status) values (6, 'Joye', 'Gobolos', 'jgobolos5', 'jgobolos5@booking.com', true);
insert into users (id, first_name, last_name, patronymic, email, status) values (7, 'Dru', 'Durham', 'ddurham6', 'ddurham6@deliciousdays.com', false);
insert into users (id, first_name, last_name, patronymic, email, status) values (8, 'Job', 'Woolway', 'jwoolway7', 'jwoolway7@weebly.com', true);
insert into users (id, first_name, last_name, patronymic, email, status) values (9, 'Henriette', 'Cestard', 'hcestard8', 'hcestard8@usda.gov', true);
insert into users (id, first_name, last_name, patronymic, email, status) values (10, 'Alys', 'Greensides', 'agreensides9', 'agreensides9@phoca.cz', false);
--Generated by https://www.mockaroo.com/